from .nodes.converse_text import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS
from .nodes.converse_text import NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY
from .nodes.converse_vision import NODE_CLASS_MAPPINGS as VISION_MAPPINGS
from .nodes.converse_vision import NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY
from .nodes.nova_canvas import NODE_CLASS_MAPPINGS as NOVA_MAPPINGS
from .nodes.nova_canvas import NODE_DISPLAY_NAME_MAPPINGS as NOVA_DISPLAY
from .nodes.nova_reel import NODE_CLASS_MAPPINGS as REEL_MAPPINGS
from .nodes.nova_reel import NODE_DISPLAY_NAME_MAPPINGS as REEL_DISPLAY
from .nodes.stability_image import NODE_CLASS_MAPPINGS as STABILITY_MAPPINGS
from .nodes.stability_image import NODE_DISPLAY_NAME_MAPPINGS as STABILITY_DISPLAY
from .nodes.stability_generate import NODE_CLASS_MAPPINGS as STABILITY_GEN_MAPPINGS
from .nodes.stability_generate import NODE_DISPLAY_NAME_MAPPINGS as STABILITY_GEN_DISPLAY
from .nodes.luma_video import NODE_CLASS_MAPPINGS as LUMA_MAPPINGS
from .nodes.luma_video import NODE_DISPLAY_NAME_MAPPINGS as LUMA_DISPLAY

NODE_CLASS_MAPPINGS = {**TEXT_MAPPINGS, **VISION_MAPPINGS, **NOVA_MAPPINGS, **REEL_MAPPINGS, **STABILITY_MAPPINGS, **STABILITY_GEN_MAPPINGS, **LUMA_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TEXT_DISPLAY, **VISION_DISPLAY, **NOVA_DISPLAY, **REEL_DISPLAY, **STABILITY_DISPLAY, **STABILITY_GEN_DISPLAY, **LUMA_DISPLAY}
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
