apiVersion: v1
kind: Service
metadata:
  name: comfyui-service
  labels:
    app: comfyui
spec:
  selector:
    app: comfyui
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}