apiVersion: v1
kind: Service
metadata:
  name: comfyui-service
  labels:
    app: comfyui
spec:
  selector:
    app: comfyui
  ports:
  - port: 8848
    protocol: TCP
    targetPort: 8848
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=300
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: comfyui-service
              port:
                number: 8848
