apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: comfyui-allow-ingress
  namespace: default
  labels:
    project: comfyui-on-eks
spec:
  podSelector:
    matchLabels:
      app: comfyui
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.2.0.0/20
    - ipBlock:
        cidr: 10.2.16.0/20
    - ipBlock:
        cidr: 10.2.32.0/20
    ports:
    - port: 8848
  egress:
  - to:
    - ipBlock:
        cidr: 10.2.0.0/16
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 443
      protocol: TCP
